name: Build and Push Model Server Image on Main

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  AWS_ROLE_ARN: arn:aws:iam::386145735201:role/sre-ai-interview-github-ci
  REGISTRY_IMAGE: 386145735201.dkr.ecr.us-east-2.amazonaws.com/sre-ai-interview-model-server

jobs:
  build-and-push:
    runs-on: ubuntu-22.04-arm64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: 386145735201.dkr.ecr.us-east-2.amazonaws.com

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push model server image
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile.model_server
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY_IMAGE }}:main
          build-args: |
            DANSWER_VERSION=${{ github.sha }}
          provenance: false
