name: Build and Push Web Image on Main

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-2
  AWS_ROLE_ARN: arn:aws:iam::386145735201:role/sre-ai-interview-github-ci
  REGISTRY_IMAGE: 386145735201.dkr.ecr.us-east-2.amazonaws.com/sre-ai-interview

jobs:
  build-and-push:
    runs-on:
      - runs-on
      - runner=8cpu-linux-x64
      - run-id=${{ github.run_id }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_ARN }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          registry: 386145735201.dkr.ecr.us-east-2.amazonaws.com

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push web image
        uses: docker/build-push-action@v6
        with:
          context: ./web
          file: ./web/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.REGISTRY_IMAGE }}:main
          build-args: |
            NODE_OPTIONS=--max-old-space-size=8192
          provenance: false
